package schema

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	apiv1schema "github.com/solat/lowcode-database/internal/apiv1/schema"
	"github.com/solat/lowcode-database/internal/columntype"
	"github.com/solat/lowcode-database/internal/service/shared"
	"strings"
)

func resolveTableIDTypeID(idType string) (string, error) {
	if idType == "" {
		return "uuid", nil
	}
	t, err := columntype.Resolve(idType)
	if err != nil {
		return "", fmt.Errorf("idType: %w", err)
	}
	if columntype.IsVirtual(idType) {
		return "", fmt.Errorf("idType cannot be a virtual column type %q", idType)
	}
	if t.PgType == "" {
		return "", fmt.Errorf("idType %q has no physical PG type", idType)
	}
	return idType, nil
}

func buildTableIDColumnDDL(typeID string) (string, error) {
	t, err := columntype.Resolve(typeID)
	if err != nil {
		return "", err
	}
	pgType := shared.EffectivePgType(t.PgType, t.Config)
	switch typeID {
	case "int8", "integer":
		return fmt.Sprintf("id %s PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", pgType), nil
	case "uuid":
		return fmt.Sprintf("id %s PRIMARY KEY DEFAULT gen_random_uuid()", pgType), nil
	default:
		return fmt.Sprintf("id %s PRIMARY KEY", pgType), nil
	}
}

func buildTableSystemColumnsDDL(typeID string) (string, error) {
	idPart, err := buildTableIDColumnDDL(typeID)
	if err != nil {
		return "", err
	}
	return idPart + ", updated_at timestamptz NOT NULL DEFAULT now()", nil
}

func pgTypeToLogicalID(pgType string) string {
	switch strings.ToLower(strings.TrimSpace(pgType)) {
	case "uuid":
		return "uuid"
	case "bigint", "int8":
		return "int8"
	case "integer", "int4":
		return "integer"
	case "smallint", "int2":
		return "integer"
	case "text":
		return "text"
	case "boolean", "bool":
		return "bool"
	case "jsonb":
		return "jsonb"
	case "double precision":
		return "double"
	case "numeric":
		return "number"
	case "timestamp with time zone", "timestamptz":
		return "timestamptz"
	case "date":
		return "date"
	default:
		return pgType
	}
}

func isIntegerIDPgType(pgType string) bool {
	switch strings.ToLower(strings.TrimSpace(pgType)) {
	case "bigint", "int8", "integer", "int4", "smallint", "int2":
		return true
	default:
		return false
	}
}

type idPgQuerier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

func PageTokenIDCompare(baseAlias, idPgType string, argIdx int) string {
	if isIntegerIDPgType(idPgType) {
		return fmt.Sprintf("%s.id > $%d::bigint", baseAlias, argIdx)
	}
	if strings.EqualFold(idPgType, "uuid") {
		return fmt.Sprintf("%s.id > $%d", baseAlias, argIdx)
	}
	return fmt.Sprintf("%s.id::text > $%d", baseAlias, argIdx)
}

func (s *Schema) LoadTableIDPgType(ctx context.Context, schemaName, tableName string) (string, error) {
	data, err := s.B.Tenants.DataPool(ctx)
	if err != nil {
		return "", err
	}
	return loadPhysicalIDPgType(ctx, data, schemaName, tableName)
}

func loadPhysicalIDPgType(ctx context.Context, db idPgQuerier, schemaName, tableName string) (string, error) {
	const sql = `
		SELECT data_type
		FROM information_schema.columns
		WHERE table_schema = $1 AND table_name = $2 AND column_name = 'id'
	`
	var pgType string
	err := db.QueryRow(ctx, sql, schemaName, tableName).Scan(&pgType)
	if err == pgx.ErrNoRows {
		return "", fmt.Errorf("physical table %s.%s has no id column", schemaName, tableName)
	}
	if err != nil {
		return "", err
	}
	return pgType, nil
}

func (s *Schema) fillTableIDType(ctx context.Context, t *apiv1schema.Table) error {
	if t == nil || t.SchemaName == "" || t.Name == "" {
		return nil
	}
	pgType, err := s.LoadTableIDPgType(ctx, t.SchemaName, t.Name)
	if err != nil {
		return err
	}
	t.IdType = pgTypeToLogicalID(pgType)
	return nil
}

func (s *Schema) fillTableIDTypes(ctx context.Context, tables []*apiv1schema.Table) error {
	if len(tables) == 0 {
		return nil
	}
	data, err := s.B.Tenants.DataPool(ctx)
	if err != nil {
		return err
	}
	bySchema := map[string][]*apiv1schema.Table{}
	for _, t := range tables {
		if t == nil {
			continue
		}
		schema := t.SchemaName
		if schema == "" {
			schema = "public"
		}
		bySchema[schema] = append(bySchema[schema], t)
	}
	for schema, group := range bySchema {
		names := make([]string, len(group))
		for i, t := range group {
			names[i] = t.Name
		}
		const q = `
			SELECT table_name, data_type
			FROM information_schema.columns
			WHERE table_schema = $1 AND column_name = 'id' AND table_name = ANY($2)
		`
		rows, err := data.Query(ctx, q, schema, names)
		if err != nil {
			return err
		}
		typesByTable := map[string]string{}
		for rows.Next() {
			var tableName, pgType string
			if err := rows.Scan(&tableName, &pgType); err != nil {
				rows.Close()
				return err
			}
			typesByTable[tableName] = pgType
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return err
		}
		rows.Close()
		for _, t := range group {
			if pgType, ok := typesByTable[t.Name]; ok {
				t.IdType = pgTypeToLogicalID(pgType)
			}
		}
	}
	return nil
}
