package schema

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/monoposer/lowcode-database/internal/columntype"
	"github.com/monoposer/lowcode-database/internal/service/shared"
	"strings"
)

func resolveTableIDTypeID(idType string) (string, error) {
	if idType == "" {
		return "uuid", nil
	}
	switch idType {
	case "uuid", "number", "text":
		return idType, nil
	default:
		if _, err := columntype.Resolve(idType); err == nil && !columntype.IsVirtual(idType) {
			t, _ := columntype.Get(idType)
			if t.PgType != "" {
				return idType, nil
			}
		}
		return "", fmt.Errorf("idType: unsupported %q (use uuid, number, or text)", idType)
	}
}

func buildTableIDColumnDDL(typeID string) (string, error) {
	switch typeID {
	case "number":
		return "id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", nil
	case "uuid":
		return "id uuid PRIMARY KEY DEFAULT gen_random_uuid()", nil
	case "text":
		return "id text PRIMARY KEY", nil
	default:
		t, err := columntype.Resolve(typeID)
		if err != nil {
			return "", err
		}
		pgType := shared.EffectivePgType(t.PgType, t.Config)
		return fmt.Sprintf("id %s PRIMARY KEY", pgType), nil
	}
}

func buildTableSystemColumnsDDL(typeID string) (string, error) {
	idPart, err := buildTableIDColumnDDL(typeID)
	if err != nil {
		return "", err
	}
	return idPart + ", updated_at timestamptz NOT NULL DEFAULT now()", nil
}

func pgTypeToLogicalID(pgType string) string {
	switch strings.ToLower(strings.TrimSpace(pgType)) {
	case "uuid":
		return "uuid"
	case "bigint", "int8", "integer", "int4", "smallint", "int2":
		return "number"
	case "text":
		return "text"
	case "boolean", "bool":
		return "boolean"
	case "jsonb", "json":
		return "jsonb"
	case "double precision", "float8", "numeric":
		return "number"
	case "timestamp with time zone", "timestamptz", "timestamp", "date":
		return "datetime"
	default:
		return pgType
	}
}

func isIntegerIDPgType(pgType string) bool {
	switch strings.ToLower(strings.TrimSpace(pgType)) {
	case "bigint", "int8", "integer", "int4", "smallint", "int2":
		return true
	default:
		return false
	}
}

type idPgQuerier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

func PageTokenIDCompare(baseAlias, idPgType string, argIdx int) string {
	if isIntegerIDPgType(idPgType) {
		return fmt.Sprintf("%s.id > $%d::bigint", baseAlias, argIdx)
	}
	if strings.EqualFold(idPgType, "uuid") {
		return fmt.Sprintf("%s.id > $%d", baseAlias, argIdx)
	}
	return fmt.Sprintf("%s.id::text > $%d", baseAlias, argIdx)
}

func (s *Schema) LoadTableIDPgType(ctx context.Context, schemaName, tableName string) (string, error) {
	data, err := s.B.Tenants.DataPool(ctx)
	if err != nil {
		return "", err
	}
	return loadPhysicalIDPgType(ctx, data, schemaName, tableName)
}

func loadPhysicalIDPgType(ctx context.Context, db idPgQuerier, schemaName, tableName string) (string, error) {
	const sql = `
		SELECT data_type
		FROM information_schema.columns
		WHERE table_schema = $1 AND table_name = $2 AND column_name = 'id'
	`
	var pgType string
	err := db.QueryRow(ctx, sql, schemaName, tableName).Scan(&pgType)
	if err == pgx.ErrNoRows {
		return "", fmt.Errorf("physical table %s.%s has no id column", schemaName, tableName)
	}
	if err != nil {
		return "", err
	}
	return pgType, nil
}

func (s *Schema) fillTableIDType(ctx context.Context, t *Table) error {
	if t == nil || t.Name == "" {
		return nil
	}
	if t.IdType == "" {
		t.IdType = "uuid"
	}
	return nil
}

func (s *Schema) fillTableIDTypes(_ context.Context, tables []*Table) error {
	for _, t := range tables {
		if t == nil {
			continue
		}
		if t.IdType == "" {
			t.IdType = "uuid"
		}
	}
	return nil
}
